[azure_sql]
connection_string = "DRIVER={ODBC Driver 18 for SQL Server};SERVER=tcp:sherpatestdb.database.windows.net,1433;DATABASE=SherpaDB;UID=sqladmin;PWD=Browassupcunt6969;Encrypt=yes;TrustServerCertificate=no;Connection Timeout=60;"

[auth]
redirect_uri = "http://localhost:8502/oauth2callback"
cookie_secret = "xxx"

[auth.microsoft]
client_id = "3cec6b08-2ade-4e59-841c-01b80f50fcc7"
client_secret = "xFL8Q~Bd7vmfzmQHjiaX2Tg4L6MSv~WtJlDS4c7P"
server_metadata_url = "https://login.microsoftonline.com/beee1775-5dd8-4686-99ef-91bb1b94d40d/v2.0/.well-known/openid-configuration"